info:
  namespace: galactus
categories:
  galactus:
    enabled: true
    name: '&5&lGalactus'
    icon: galactus:galactus_sword
    permission: ia.menu.galactus
    items:
      - galactus:galactus_helmet
      - galactus:galactus_chestplate
      - galactus:galactus_leggings
      - galactus:galactus_boots
      - galactus:galactus_sword
      - galactus:galactus_axe
      - galactus:galactus_pickaxe
      - galactus:galactus_shovel
      - galactus:galactus_hoe
      - galactus:galactus_mace
      - galactus:galactus_spear
      - galactus:galactus_trident
      - galactus:galactus_bow
