info:
  namespace: galactus
items:
  galactus_helmet:
    enabled: true
    display_name: '&5&lGalactus Helmet'
    lore:
      - '&f'
      - '&o&7Forged in the heart of a dying star,'
      - '&o&7worn by the one who devours worlds.'
      - '&f'
      - '&d+5 hearts, +8 toughness, +10% speed, +2 damage per piece'
      - '&f'
      - '&4Admin only'
    permission: galactus.helmet
    behaviours:
      hat: true
    resource:
      material: LEATHER_HORSE_ARMOR
      generate: false
      model_path: item/galactus_helmet
    durability:
      max_custom_durability: 99999
    attribute_modifiers:
      head:
        armor: 8
        armorToughness: 8
        knockbackResistance: 0.3
        maxHealth: 10
        movementSpeed: 0.01
        attackDamage: 2
  galactus_chestplate:
    enabled: true
    display_name: '&5&lGalactus Chestplate'
    lore:
      - '&f'
      - '&o&7Forged in the heart of a dying star,'
      - '&o&7worn by the one who devours worlds.'
      - '&f'
      - '&d+5 hearts, +8 toughness, +10% speed, +2 damage per piece'
      - '&f'
      - '&4Admin only'
    permission: galactus.chestplate
    resource:
      material: NETHERITE_CHESTPLATE
      generate: true
      textures:
        - item/galactus_chestplate
    durability:
      max_custom_durability: 99999
    equipment:
      id: galactus:galactus_armor
      slot: CHEST
      slot_attribute_modifiers:
        armor: 14
        armorToughness: 8
        knockbackResistance: 0.3
        maxHealth: 10
        movementSpeed: 0.01
        attackDamage: 2
  galactus_leggings:
    enabled: true
    display_name: '&5&lGalactus Leggings'
    lore:
      - '&f'
      - '&o&7Forged in the heart of a dying star,'
      - '&o&7worn by the one who devours worlds.'
      - '&f'
      - '&d+5 hearts, +8 toughness, +10% speed, +2 damage per piece'
      - '&f'
      - '&4Admin only'
    permission: galactus.leggings
    resource:
      material: NETHERITE_LEGGINGS
      generate: true
      textures:
        - item/galactus_leggings
    durability:
      max_custom_durability: 99999
    equipment:
      id: galactus:galactus_armor
      slot: LEGS
      slot_attribute_modifiers:
        armor: 12
        armorToughness: 8
        knockbackResistance: 0.3
        maxHealth: 10
        movementSpeed: 0.01
        attackDamage: 2
  galactus_boots:
    enabled: true
    display_name: '&5&lGalactus Boots'
    lore:
      - '&f'
      - '&o&7Forged in the heart of a dying star,'
      - '&o&7worn by the one who devours worlds.'
      - '&f'
      - '&d+5 hearts, +8 toughness, +10% speed, +2 damage per piece'
      - '&f'
      - '&4Admin only'
    permission: galactus.boots
    resource:
      material: NETHERITE_BOOTS
      generate: true
      textures:
        - item/galactus_boots
    durability:
      max_custom_durability: 99999
    equipment:
      id: galactus:galactus_armor
      slot: FEET
      slot_attribute_modifiers:
        armor: 8
        armorToughness: 8
        knockbackResistance: 0.3
        maxHealth: 10
        movementSpeed: 0.01
        attackDamage: 2
  galactus_sword:
    enabled: true
    display_name: '&5&lGalactic Blade'
    lore:
      - '&f'
      - '&o&7Forged in the heart of a dying star,'
      - '&o&7worn by the one who devours worlds.'
      - '&f'
      - '&d+32 attack damage'
      - '&f'
      - '&4Admin only'
    permission: galactus.sword
    resource:
      material: NETHERITE_SWORD
      generate: false
      model_path: item/galactus_sword
    durability:
      max_custom_durability: 99999
    attribute_modifiers:
      mainhand:
        attackDamage: 32
        attackSpeed: 2.0
  galactus_axe:
    enabled: true
    display_name: '&5&lStar-Cleaver Axe'
    lore:
      - '&f'
      - '&o&7Forged in the heart of a dying star,'
      - '&o&7worn by the one who devours worlds.'
      - '&f'
      - '&d+38 attack damage'
      - '&f'
      - '&4Admin only'
    permission: galactus.axe
    resource:
      material: NETHERITE_AXE
      generate: false
      model_path: item/galactus_axe
    durability:
      max_custom_durability: 99999
    attribute_modifiers:
      mainhand:
        attackDamage: 38
        attackSpeed: 1.2
  galactus_pickaxe:
    enabled: true
    display_name: '&5&lWorldbreaker Pickaxe'
    lore:
      - '&f'
      - '&o&7Forged in the heart of a dying star,'
      - '&o&7worn by the one who devours worlds.'
      - '&f'
      - '&d+20 attack damage'
      - '&f'
      - '&4Admin only'
    permission: galactus.pickaxe
    resource:
      material: NETHERITE_PICKAXE
      generate: false
      model_path: item/galactus_pickaxe
    durability:
      max_custom_durability: 99999
    attribute_modifiers:
      mainhand:
        attackDamage: 20
        attackSpeed: 1.6
  galactus_shovel:
    enabled: true
    display_name: '&5&lMoondust Shovel'
    lore:
      - '&f'
      - '&o&7Forged in the heart of a dying star,'
      - '&o&7worn by the one who devours worlds.'
      - '&f'
      - '&d+20 attack damage'
      - '&f'
      - '&4Admin only'
    permission: galactus.shovel
    resource:
      material: NETHERITE_SHOVEL
      generate: false
      model_path: item/galactus_shovel
    durability:
      max_custom_durability: 99999
    attribute_modifiers:
      mainhand:
        attackDamage: 20
        attackSpeed: 1.4
  galactus_hoe:
    enabled: true
    display_name: '&5&lHarvester of Worlds'
    lore:
      - '&f'
      - '&o&7Forged in the heart of a dying star,'
      - '&o&7worn by the one who devours worlds.'
      - '&f'
      - '&d+18 attack damage'
      - '&f'
      - '&4Admin only'
    permission: galactus.hoe
    resource:
      material: NETHERITE_HOE
      generate: false
      model_path: item/galactus_hoe
    durability:
      max_custom_durability: 99999
    attribute_modifiers:
      mainhand:
        attackDamage: 18
        attackSpeed: 4.0
  galactus_mace:
    enabled: true
    display_name: '&5&lPlanetcrusher Mace'
    lore:
      - '&f'
      - '&o&7Forged in the heart of a dying star,'
      - '&o&7worn by the one who devours worlds.'
      - '&f'
      - '&d+30 attack damage'
      - '&f'
      - '&4Admin only'
    permission: galactus.mace
    resource:
      material: MACE
      generate: false
      model_path: item/galactus_mace
    durability:
      max_custom_durability: 99999
    attribute_modifiers:
      mainhand:
        attackDamage: 30
        attackSpeed: 1.0
        knockbackResistance: 0.5
  galactus_spear:
    enabled: true
    display_name: '&5&lComet Spear'
    lore:
      - '&f'
      - '&o&7Forged in the heart of a dying star,'
      - '&o&7worn by the one who devours worlds.'
      - '&f'
      - '&d+30 attack damage'
      - '&f'
      - '&4Admin only'
    permission: galactus.spear
    resource:
      material: NETHERITE_SPEAR
      generate: false
      model_path: item/galactus_spear
    durability:
      max_custom_durability: 99999
    attribute_modifiers:
      mainhand:
        attackDamage: 30
        attackSpeed: 1.4
        movementSpeed: 0.02
  galactus_trident:
    enabled: true
    display_name: '&5&lTidebringer of Andromeda'
    lore:
      - '&f'
      - '&o&7Forged in the heart of a dying star,'
      - '&o&7worn by the one who devours worlds.'
      - '&f'
      - '&d+30 attack damage'
      - '&f'
      - '&4Admin only'
    permission: galactus.trident
    resource:
      material: TRIDENT
      generate: false
      model_path: item/galactus_trident
    durability:
      max_custom_durability: 99999
    attribute_modifiers:
      mainhand:
        attackDamage: 30
        attackSpeed: 1.4
  galactus_bow:
    enabled: true
    display_name: '&5&lNebula Bow'
    lore:
      - '&f'
      - '&o&7Forged in the heart of a dying star,'
      - '&o&7worn by the one who devours worlds.'
      - '&f'
      - '&4Admin only'
    permission: galactus.bow
    resource:
      material: BOW
      generate: false
      model_path: item/galactus_bow
      icon: item/galactus_bow_icon
    durability:
      max_custom_durability: 99999
